name: Android CI

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          accept-android-sdk-licenses: true

      - name: Install SDK packages (API 34 preferred, 35 fallback)
        shell: bash
        run: |
          set -euxo pipefail
          sdkmanager "platform-tools" || true
          sdkmanager "platforms;android-34" || sdkmanager "platforms;android-35" || true
          sdkmanager "build-tools;34.0.0" || sdkmanager "build-tools;35.0.0" || true

      - name: Install Gradle 8.4 (official zip)
        shell: bash
        run: |
          set -euxo pipefail
          GRADLE_VER=8.4
          curl -L "https://services.gradle.org/distributions/gradle-${GRADLE_VER}-bin.zip" -o gradle.zip
          unzip -q gradle.zip -d "$HOME/gradle"
          echo "$HOME/gradle/gradle-${GRADLE_VER}/bin" >> "$GITHUB_PATH"
          gradle --version

      - name: Build Debug APK (with full diagnostics)
        shell: bash
        run: |
          set -euxo pipefail
          gradle -q projects || true
          gradle :app:dependencies --configuration debugRuntimeClasspath > deps.txt || true
          ( gradle :app:checkDebugAarMetadata --stacktrace --console=plain --info || true ) | tee build.log
          ( gradle :app:assembleDebug --stacktrace --console=plain --info || true ) | tee -a build.log

      - name: List outputs (debug)
        if: always()
        shell: bash
        run: |
          set -euxo pipefail
          echo "=== SEARCHING FOR APK/AAB FILES ==="
          find . -maxdepth 6 -type f \( -name '*.apk' -o -name '*.aab' \) -print | sed 's/^/FOUND: /' || true
          echo "===================================="

      - name: Upload any APK/AAB (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            **/outputs/apk/**/*.apk
            **/outputs/bundle/**/*.aab
          if-no-files-found: warn

      - name: Upload diagnostics (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: gradle-diag
          path: |
            build.log
            deps.txt
