name: Android CI
on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - uses: android-actions/setup-android@v3
        with:
          accept-android-sdk-licenses: true

      - name: Install SDK packages (prefer 34, fallback 35)
        shell: bash
        run: |
          set -euxo pipefail
          sdkmanager "platform-tools" || true
          sdkmanager "platforms;android-34" || sdkmanager "platforms;android-35" || true
          sdkmanager "build-tools;34.0.0"  || sdkmanager "build-tools;35.0.0"  || true

      - name: Install Gradle 8.4 (runner-local)
        shell: bash
        run: |
          set -euxo pipefail
          v=8.4
          curl -L "https://services.gradle.org/distributions/gradle-${v}-bin.zip" -o gradle.zip
          unzip -q gradle.zip -d "$HOME/gradle"
          echo "$HOME/gradle/gradle-${v}/bin" >> "$GITHUB_PATH"
          gradle --version

      - name: Detect Android application module
        id: detect
        shell: bash
        run: |
          set -e
          HIT="$(grep -RIl --include=build.gradle --include=build.gradle.kts 'com.android.application' . | head -n1 || true)"
          [ -n "$HIT" ] || { echo "No module with 'com.android.application' found."; exit 1; }
          MOD_DIR="$(dirname "$HIT")"; MOD_REL="${MOD_DIR#./}"; MOD_NAME="${MOD_REL//\//:}"
          echo "module_dir=$MOD_REL"    >> "$GITHUB_OUTPUT"
          echo "module_path=:$MOD_NAME" >> "$GITHUB_OUTPUT"
          echo "Module: $MOD_REL | Gradle path ::$MOD_NAME"

      - name: Build Debug APK (strict + logs)
        shell: bash
        run: |
          set -euxo pipefail
          export GRADLE_OPTS="-Dorg.gradle.console=plain"
          gradle "${{ steps.detect.outputs.module_path }}:assembleDebug" --stacktrace --info --no-daemon | tee build.log

          echo "=== SEARCH APK/AAB (whole repo) ==="
          find . -maxdepth 10 -type f \( -name '*.apk' -o -name '*.aab' \) -print | sed 's/^/FOUND: /' || true

          echo "=== SEARCH inside module build dir ==="
          if [ -d "${{ steps.detect.outputs.module_dir }}/build" ]; then
            find "${{ steps.detect.outputs.module_dir }}/build" -maxdepth 8 -type f -print | sed 's/^/BUILDFILE: /' || true
          else
            echo "No module build dir."
          fi

          # Fail explicit dacă nu există niciun APK în outputs
          if ! find "${{ steps.detect.outputs.module_dir }}/build/outputs/apk" -type f -name '*.apk' | grep -q . ; then
            echo "No APK found under ${{ steps.detect.outputs.module_dir }}/build/outputs/apk"
            echo "------ tail build.log ------"
            tail -n 200 build.log || true
            # NU mai dăm exit 1 aici, ca să putem încărca artefactele de diagnostic
          fi

      - name: Upload ANY APK/AAB (repo-wide)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            **/*.apk
            **/*.aab
          if-no-files-found: warn
          retention-days: 7

      - name: Upload module build directory (diagnostics)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: module-build-dir
          path: ${{ steps.detect.outputs.module_dir }}/build/**
          if-no-files-found: warn
          retention-days: 7

      - name: Upload build.log (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: gradle-build-log
          path: build.log
          retention-days: 14
