name: Android CI

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          accept-android-sdk-licenses: true

      - name: Install SDK packages (prefer 34, fallback 35)
        shell: bash
        run: |
          set -euxo pipefail
          sdkmanager "platform-tools" || true
          sdkmanager "platforms;android-34" || sdkmanager "platforms;android-35" || true
          sdkmanager "build-tools;34.0.0"  || sdkmanager "build-tools;35.0.0"  || true

      - name: Install Gradle 8.4 (official zip)
        shell: bash
        run: |
          set -euxo pipefail
          v=8.4
          curl -L "https://services.gradle.org/distributions/gradle-${v}-bin.zip" -o gradle.zip
          unzip -q gradle.zip -d "$HOME/gradle"
          echo "$HOME/gradle/gradle-${v}/bin" >> "$GITHUB_PATH"
          gradle --version

      - name: Detect Android application module
        id: detect
        shell: bash
        run: |
          set -e
          HIT="$(grep -RIl --include=build.gradle --include=build.gradle.kts 'com.android.application' . | head -n1 || true)"
          if [ -z "$HIT" ]; then
            echo "Nu am găsit niciun modul cu 'com.android.application' în repo." >&2
            exit 1
          fi
          MOD_DIR="$(dirname "$HIT")"
          MOD_REL="${MOD_DIR#./}"
          MOD_NAME="${MOD_REL//\//:}"
          echo "module_dir=$MOD_REL"    >> "$GITHUB_OUTPUT"
          echo "module_path=:$MOD_NAME" >> "$GITHUB_OUTPUT"
          echo "Found module dir: $MOD_REL  | Gradle path: :$MOD_NAME"

      - name: Build Debug APK (capture logs)
        shell: bash
        run: |
          set -euxo pipefail
          ( gradle "${{ steps.detect.outputs.module_path }}:checkDebugAarMetadata" --stacktrace --console=plain --info || true ) | tee build.log
          ( gradle "${{ steps.detect.outputs.module_path }}:assembleDebug"         --stacktrace --console=plain --info || true ) | tee -a build.log

      - name: List outputs (debug)
        if: always()
        shell: bash
        run: |
          set -euxo pipefail
          echo "=== SEARCH APK/AAB ==="
          find . -maxdepth 9 -type f \( -name '*.apk' -o -name '*.aab' \) -print | sed 's/^/FOUND: /' || true
          echo "=== MODULE BUILD DIR ==="
          [ -d "${{ steps.detect.outputs.module_dir }}/build" ] && find "${{ steps.detect.outputs.module_dir }}/build" -maxdepth 6 -type f -print | sed 's/^/BUILDFILE: /' || echo "No module build dir."

      - name: Upload APK/AAB (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            ${{ steps.detect.outputs.module_dir }}/build/outputs/apk/**/*.apk
            ${{ steps.detect.outputs.module_dir }}/build/outputs/bundle/**/*.aab
          if-no-files-found: warn

      - name: Upload build log (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: gradle-build-log
          path: build.log
