name: Android CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # fallback dacă nu e setat - setup-android acționează de obicei asupra acestei variabile
      ANDROID_SDK_ROOT: /usr/local/lib/android/sdk

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      # Instalează doar cmdline-tools cu acțiunea oficială (fără bloc packages care poate eșua)
      - name: Set up Android SDK (cmdline-tools)
        uses: android-actions/setup-android@v3
        with:
          accept-android-sdk-licenses: true
          cmdline-tools-version: 11076708

      # Pas explicit pentru a instala platform-tools, platform-34 și build-tools 34.0.0
      # Motiv: instalarea prin blocul packages la setup-android a dat exit code 1 în log.
      - name: Install required Android SDK packages
        run: |
          set -e
          # Asigură variabila de mediu
          export ANDROID_SDK_ROOT="${ANDROID_SDK_ROOT:-/usr/local/lib/android/sdk}"

          # posibile locații pentru sdkmanager
          SDKMANAGER="$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager"
          if [ ! -x "$SDKMANAGER" ]; then
            SDKMANAGER="$ANDROID_SDK_ROOT/cmdline-tools/bin/sdkmanager"
          fi
          if [ ! -x "$SDKMANAGER" ]; then
            SDKMANAGER="/usr/local/lib/android/sdk/cmdline-tools/latest/bin/sdkmanager"
          fi

          echo "Using sdkmanager at: $SDKMANAGER"
          # actualizează repo și instalează pachetele necesare non-interactiv
          yes | "$SDKMANAGER" --sdk_root="$ANDROID_SDK_ROOT" "platform-tools" "platforms;android-34" "build-tools;34.0.0"

          # acceptă licențele (unele pachete pot cere explicit accept)
          yes | "$SDKMANAGER" --sdk_root="$ANDROID_SDK_ROOT" --licenses || true

      - name: Install Gradle 8.7 via SDKMAN (fără acțiuni depreciate)
        run: |
          curl -s "https://get.sdkman.io" | bash
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          sdk install gradle 8.7
          gradle --version

      - name: Build Debug APK
        run: ./gradlew assembleDebug
        # folosește ./gradlew în loc de gradle direct pentru consistență cu wrapper-ul proiectului

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: StealthCam-debug
          path: app/build/outputs/apk/debug/*.apk
