name: Android CI
on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Set up Android SDK (cmdline-tools)
        uses: android-actions/setup-android@v3
        with:
          accept-android-sdk-licenses: true
          cmdline-tools-version: 11076708

      - name: Install SDK packages (prefer 34, fallback 35)
        shell: bash
        run: |
          set -euxo pipefail
          sdkmanager "platform-tools" || true
          sdkmanager "platforms;android-34" || sdkmanager "platforms;android-35" || true
          sdkmanager "build-tools;34.0.0" || sdkmanager "build-tools;35.0.0" || true

      - name: Install Gradle 8.4 (official zip)
        shell: bash
        run: |
          set -euxo pipefail
          GRADLE_VER=8.4
          curl -L "https://services.gradle.org/distributions/gradle-${GRADLE_VER}-bin.zip" -o gradle.zip
          unzip -q gradle.zip -d "$HOME/gradle"
          echo "$HOME/gradle/gradle-${GRADLE_VER}/bin" >> "$GITHUB_PATH"
          gradle --version

      - name: Diagnostics + Build
        shell: bash
        run: |
          set -euxo pipefail
          # 1) Proiecte + arbore dependențe
          gradle -q projects || true
          gradle :app:dependencies --configuration debugRuntimeClasspath > deps.txt || true
          gradle :app:dependencyInsight --configuration debugRuntimeClasspath --dependency lifecycle-livedata > insight-livedata.txt || true
          gradle :app:dependencyInsight --configuration debugRuntimeClasspath --dependency kotlinx-coroutines-core > insight-coroutines.txt || true
          # 2) Rulăm task-ul care pică cu log maximal; nu oprim pe eroare ca să salvăm logul
          ( gradle :app:checkDebugAarMetadata --stacktrace --debug --console=plain || true ) | tee build.log
          # 3) Dacă a trecut metadata, încercăm și assemble, dar nu blocăm artifactele
          ( gradle :app:assembleDebug --stacktrace --debug --console=plain || true ) | tee -a build.log

      - name: Upload diagnostics (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: gradle-diag
          path: |
            build.log
            deps.txt
            insight-*.txt

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: StealthCam-debug
          path: app/build/outputs/apk/debug/*.apk
          
