GitHub Copilot Chat Assistant — conținutul .github/workflows/android.yml (ref 56ae31af925f97908a104078215b11e7e217c096):

```yaml
name: Android CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Android SDK (cmdline-tools + pachete)
        uses: android-actions/setup-android@v3
        with:
          accept-android-sdk-licenses: true
          # opțional: alege versiunea cmdline-tools
          cmdline-tools-version: 11076708
          packages: |
            platforms;android-34
            build-tools;34.0.0
            platform-tools

      - name: Install Gradle 8.7 via SDKMAN (fără acțiuni depreciate)
        run: |
          curl -s "https://get.sdkman.io" | bash
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          sdk install gradle 8.7
          gradle --version

      - name: Build Debug APK
        run: gradle assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: StealthCam-debug
          path: app/build/outputs/apk/debug/*.apk
```
