- name: Setup Gradle
  uses: gradle/actions/setup-gradle@v4

- name: Make wrapper executable
  run: chmod +x "${{ steps.detect.outputs.root }}/gradlew"

- name: Build Debug APK
  shell: bash
  run: |
    set -euxo pipefail
    cd "${{ steps.detect.outputs.root }}"
    ./gradlew assembleDebug --stacktrace --warning-mode all --info          fi
          if ! sdkmanager "build-tools;34.0.0"; then
            LATEST_BT="$(sdkmanager --list | sed -n 's/^[[:space:]]*\(build-tools;[0-9][0-9.]*\).*/\1/p' | sort -V | tail -1)"
            sdkmanager "${LATEST_BT}"
          fi
          echo "USING_API=${USING_API}" >> "$GITHUB_ENV"

      - name: Detect Gradle project root
        id: detect
        shell: bash
        run: |
          set -e
          ROOT="$(git ls-files | grep -E '(^|/)(settings\.gradle(\.kts)?|build\.gradle(\.kts)?)$' | xargs -r -n1 dirname | sort -u | head -n1)"
          [ -n "$ROOT" ] || { echo "No Gradle settings/build file found"; exit 1; }
          echo "root=$ROOT" >> "$GITHUB_OUTPUT"

      - name: Align compile/target SDK if fallback used
        if: env.USING_API != '34'
        shell: bash
        run: |
          API="${USING_API}"
          ROOT="${{ steps.detect.outputs.root }}"
          sed -i "s/compileSdkVersion [0-9][0-9]*/compileSdkVersion ${API}/" "$ROOT/app/build.gradle" || true
          sed -i "s/targetSdkVersion [0-9][0-9]*/targetSdkVersion ${API}/" "$ROOT/app/build.gradle" || true

      - name: Install Gradle 8.4 via SDKMAN
        shell: bash
        run: |
          curl -s "https://get.sdkman.io" | bash
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          sdk install gradle 8.4
          gradle --version

      - name: Build Debug APK
        shell: bash
        run: |
          set -euxo pipefail
          cd "${{ steps.detect.outputs.root }}"
          gradle assembleDebug --stacktrace --warning-mode all --info

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: StealthCam-debug
          path: ${{ steps.detect.outputs.root }}/app/build/outputs/apk/debug/*.apk
