name: Android CI
on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          accept-android-sdk-licenses: true
          cmdline-tools-version: 11076708

      - name: Install SDK packages (with fallback)
        shell: bash
        run: |
          set -euxo pipefail
          sdkmanager --list || true
          sdkmanager "platform-tools" || true
          if ! sdkmanager "platforms;android-34"; then
            LATEST_PLATFORM="$(sdkmanager --list | sed -n 's/^[[:space:]]*\(platforms;android-[0-9]\+\).*/\1/p' | sort -V | tail -1)"
            sdkmanager "${LATEST_PLATFORM}"
            USING_API="${LATEST_PLATFORM##*android-}"
          else
            USING_API="34"
          fi
          if ! sdkmanager "build-tools;34.0.0"; then
            LATEST_BT="$(sdkmanager --list | sed -n 's/^[[:space:]]*\(build-tools;[0-9][0-9.]*\).*/\1/p' | sort -V | tail -1)"
            sdkmanager "${LATEST_BT}"
          fi
          echo "USING_API=${USING_API}" >> "$GITHUB_ENV"

      - name: Detect Gradle project root
        id: detect
        shell: bash
        run: |
          set -e
          ROOT="$(git ls-files | grep -E '(^|/)(settings\.gradle(\.kts)?|build\.gradle(\.kts)?)$' | xargs -r -n1 dirname | sort -u | head -n1)"
          [ -n "$ROOT" ] || { echo "No Gradle settings/build file found"; exit 1; }
          echo "root=$ROOT" >> "$GITHUB_OUTPUT"
<<<<<<< HEAD
          echo "Gradle root: $ROOT"
=======
>>>>>>> 2271b0a (CI: fix YAML (no merged lines), robust SDK + auto-detect Gradle root)

      - name: Align compile/target SDK if fallback used
        if: env.USING_API != '34'
        shell: bash
        run: |
          API="${USING_API}"
          ROOT="${{ steps.detect.outputs.root }}"
          sed -i "s/compileSdkVersion [0-9][0-9]*/compileSdkVersion ${API}/" "$ROOT/app/build.gradle" || true
          sed -i "s/targetSdkVersion [0-9][0-9]*/targetSdkVersion ${API}/" "$ROOT/app/build.gradle" || true

      - name: Install Gradle 8.4 via SDKMAN
        shell: bash
        run: |
          curl -s "https://get.sdkman.io" | bash
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          sdk install gradle 8.4
          gradle --version

<<<<<<< HEAD
      - name: Build Debug APK
        shell: bash
        run: |
          set -euxo pipefail
          cd "${{ steps.detect.outputs.root }}"
          gradle assembleDebug --stacktrace --warning-mode all --info

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: StealthCam-debug
          path: ${{ steps.detect.outputs.root }}/app/build/outputs/apk/debug/*.apk          gradle --version

      - name: Build Debug APK
        shell: bash
        run: |
          cd "${{ steps.detect.outputs.root }}"
          gradle assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: StealthCam-debug
          path: ${{ steps.detect.outputs.root }}/app/build/outputs/apk/debug/*.apk      - name: Install Gradle 8.4 via SDKMAN (compatible with AGP 8.2.2)
        shell: bash
        run: |
          curl -s "https://get.sdkman.io" | bash
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          sdk install gradle 8.4
          gradle --version

      - name: Build Debug APK
        shell: bash
        run: |
          cd "${{ steps.detect.outputs.root }}"
          gradle assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: StealthCam-debug
          path: ${{ steps.detect.outputs.root }}/app/build/outputs/apk/debug/*.apk        run: |
          API="${USING_API}"
          ROOT="${{ steps.detect.outputs.root }}"
          echo "Adjusting compile/target SDK in $ROOT to ${API}"
          sed -i "s/compileSdkVersion [0-9][0-9]*/compileSdkVersion ${API}/" "$ROOT/app/build.gradle" || true
          sed -i "s/targetSdkVersion [0-9][0-9]*/targetSdkVersion ${API}/" "$ROOT/app/build.gradle" || true

      - name: Install Gradle 8.4 via SDKMAN (compatible with AGP 8.2.2)
        shell: bash
        run: |
          curl -s "https://get.sdkman.io" | bash
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          sdk install gradle 8.4
          gradle --version

      - name: Build Debug APK
        shell: bash
        run: |
          cd "${{ steps.detect.outputs.root }}"
          gradle assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: StealthCam-debug
          path: ${{ steps.detect.outputs.root }}/app/build/outputs/apk/debug/*.apk
YAML

git add .github/workflows/android.yml
git commit -m "CI: auto-detect Gradle root + robust SDK install"
git push          curl -s "https://get.sdkman.io" | bash
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          sdk install gradle 8.4
          gradle --version

      # Build APK debug
      - name: Build Debug APK
        run: gradle assembleDebug

      # Upload artifact (APK)
=======
      - name: Build Debug APK
        shell: bash
        run: |
          set -euxo pipefail
          cd "${{ steps.detect.outputs.root }}"
          gradle assembleDebug --stacktrace --warning-mode all --info

>>>>>>> 2271b0a (CI: fix YAML (no merged lines), robust SDK + auto-detect Gradle root)
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: StealthCam-debug
          path: ${{ steps.detect.outputs.root }}/app/build/outputs/apk/debug/*.apk
