name: Android CI
on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          accept-android-sdk-licenses: true
          cmdline-tools-version: 11076708
      - name: Install SDK packages (with fallback)
        shell: bash
        run: |
          set -euxo pipefail
          sdkmanager "platform-tools" || true
          sdkmanager "platforms;android-34" || sdkmanager "platforms;android-35"
          sdkmanager "build-tools;34.0.0" || sdkmanager "build-tools;35.0.0" || true
      - name: Detect Gradle project root
        id: detect
        shell: bash
        run: |
          ROOT="$(git ls-files | grep -E '(^|/)(settings\.gradle(\.kts)?|build\.gradle(\.kts)?)$' | xargs -r -n1 dirname | sort -u | head -n1)"
          [ -n "$ROOT" ] || { echo "No Gradle settings/build file found"; exit 1; }
          echo "root=$ROOT" >> "$GITHUB_OUTPUT"
      - name: Make wrapper executable
        run: chmod +x "${{ steps.detect.outputs.root }}/gradlew" || true
      - name: Build Debug APK
        shell: bash
        run: |
          set -euxo pipefail
          cd "${{ steps.detect.outputs.root }}"
          ./gradlew assembleDebug --stacktrace --warning-mode all --info
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: StealthCam-debug
          path: ${{ steps.detect.outputs.root }}/app/build/outputs/apk/debug/*.apk
